### ISSUE TITLE
int64_of_string Does Not Work on Negative Numbers

### ISSUE THREAD

**Issue by LTibbetts** [plow-technologies/rescript-aeson#24]
## Problem

[int64_of_string](https://github.com/plow-technologies/bs-aeson/blob/master/src/Aeson_decode.ml#L88-L96) performs a check on the input string to determine if the string only contains digits. This causes an error when a negative number is encountered since `-` in not included in the digit set.

## Suggested Fix 1

Add `-` to the list of digit characters. But this could cause problems if the string is only `-`, so more thought would be required.

## Suggested Fix 2

Remove the string check entirely use the native `Int64.of_string`, catching the exception that it generates on failure, and re-throw it as a `DecodeError`.

**Comment by mchaver** [comment]
Looks like it was fixed a long time ago, but also we use different stuff now with core.
